[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/dashboard"
  to = "/.netlify/functions/dashboard"
  status = 200

[[redirects]]
  from = "/api/import"
  to = "/.netlify/functions/import-csv"
  status = 200

[[redirects]]
  from = "/api/export.csv"
  to = "/.netlify/functions/export-csv"
  status = 200
